#!/bin/sh

# The goal of this script is to download, unpack and commit the `.model` files generated by the CI.
# It will find the latest pipeline associated with the current local branch and try to fetch artifacts from it.

SCRIPT_PATH=`readlink -f $0`
SCRIPT_DIR=`dirname $SCRIPT_PATH`
REF=`git branch --show-current`

# Fetch Pipeline ID

if pipeline_id=`curl -s -f "https://invent.kde.org/api/v4/projects/17308/pipelines" | jq -e "[.[] | select(.ref == \"$REF\")][0].id"`
then
    job_url="https://invent.kde.org/api/v4/projects/17308/pipelines/$pipeline_id/jobs?scope[]=success"
    echo "Using pipeline #$pipeline_id - job url: $job_url"
else
    echo "Pipeline not found, make sure you have manually triggered a pipeline for this branch"
    exit 1
fi

# Fetch Job ID

if job_id=`curl -s -f "$job_url" | jq -e '.[] | select(.name == "neon_core_models") | .id'`
then
    artifacts_url="https://invent.kde.org/api/v4/projects/17308/jobs/$job_id/artifacts"
    echo "Using job #$job_id - artifacts url: $artifacts_url"
else
    echo "Job not found, make sure you have manually started the 'neon_core_models' job in the pipeline #$pipeline_id and it succeeded"
    exit 1
fi

# Fetch Job Artefact, Unpack & Commit

curl -s --location --output "$SCRIPT_DIR/Signed_models.zip" "$artifacts_url"
unzip "$SCRIPT_DIR/Signed_models.zip" -d "$SCRIPT_DIR/Signed_models"
success=$?

if [ $success -eq 0 ]
then
    mv "$SCRIPT_DIR"/Signed_models/*.model ./
    git add -f ./*.model
    git commit -m "Update models"
    echo "Commit done, you may verify it before pushing it"
else
    echo "Failed to download artifacts:"
    cat "$SCRIPT_DIR/Signed_models.zip" ; echo
fi

# Cleanup

rm -f "$SCRIPT_DIR/Signed_models.zip"
rm -rf "$SCRIPT_DIR/Signed_models"

exit $success