#!/bin/sh

# The goal of this script is to download, unpack and commit the `.model` files generated by the CI.
# It will find the latest pipeline associated with the current local branch and try to fetch artifacts from it.

BASE_URL="https://invent.kde.org/api/v4/projects/17308"
SCRIPT_PATH=`readlink -f $0`
SCRIPT_DIR=`dirname $SCRIPT_PATH`
DL_DIR=`mktemp -t -d model_artifactsXXX`
REF=`git branch --show-current`

cleanup() {
    rm -rf "$DL_DIR"
}

failure() {
    echo "$1"
    cleanup
    exit 1
}

# Fetch Pipeline ID

pipeline_id=`curl -s -f "$BASE_URL/pipelines" | jq -e "[.[] | select(.ref == \"$REF\")][0].id"` \
  || failure "Pipeline not found, make sure you have manually triggered a pipeline for this branch"
job_url="$BASE_URL/pipelines/$pipeline_id/jobs?scope[]=success"
echo "Using pipeline #$pipeline_id - job url: $job_url"

# Fetch Job ID

job_id=`curl -s -f "$job_url" | jq -e '.[] | select(.name == "neon_core_models") | .id'` \
  || failure "Job not found, make sure you have manually started the 'neon_core_models' job in the pipeline #$pipeline_id and it succeeded"
artifacts_url="$BASE_URL/jobs/$job_id/artifacts"
echo "Using job #$job_id - artifacts url: $artifacts_url"

# Fetch Job Artefact, Unpack & Commit

curl -s --location --output "$DL_DIR/Signed_models.zip" "$artifacts_url"
unzip -qq "$DL_DIR/Signed_models.zip" -d "$DL_DIR/Signed_models" 2> /dev/null \
  || failure "`echo "Failed to download artifacts:" ; cat "$DL_DIR/Signed_models.zip" ; echo`"
mv "$DL_DIR"/Signed_models/*.model "$SCRIPT_DIR"/
git add -f "$SCRIPT_DIR"/*.model
git commit -m "Update models"

cleanup
echo "Commit done, you may verify it before pushing"
