#!/bin/sh

# The goal of this script is to download, unpack and commit the `.model` files generated by the CI.
# It will find the latest pipeline associated with the current local branch and try to fetch artifacts from it.

# Fetch Pipeline ID

ref=`git branch --show-current`
pipeline_id=`curl "https://invent.kde.org/api/v4/projects/17308/pipelines" | jq "[.[] | select(.ref == \"$ref\")][0].id"`
if [ -z "$pipeline_id" ]; then
    echo "Pipeline not found, make sure you have manually triggered a pipeline for this branch"
    exit 1
else
    job_url="https://invent.kde.org/api/v4/projects/17308/pipelines/$pipeline_id/jobs?scope[]=success"
    echo "Using pipeline #$pipeline_id - job url: $job_url"
fi

# Fetch Job ID

job_id=`curl "$job_url" | jq '.[] | select(.name == "neon_core_models") | .id'`
if [ -z "$job_id" ]; then
    echo "Job not found, make sure you have manually started the 'neon_core_models' job in the pipeline #$pipeline_id and it succeeded"
    exit 1
else
    artifacts_url="https://invent.kde.org/api/v4/projects/17308/jobs/$job_id/artifacts"
    echo "Using job #$job_id - artifacts url: $artifacts_url"
fi

# Fetch Job Artefact

if [ -z "`curl $artifacts_url | jq '.message'`" ]; then
    rm -f /tmp/Signed_models.zip
    curl --location --output /tmp/Signed_models.zip "$artifacts_url"
else
    echo "Got the following error while fetching job artifacts:"
    curl "$artifacts_url" | jq
    exit 1
fi

# Git unpack and commit

rm -rf /tmp/Signed_models
unzip /tmp/Signed_models.zip -d /tmp/Signed_models
mv /tmp/Signed_models/*.model ./
git add -f ./*.model
git commit -m "Update models"

echo "Commit done, you may verify it before pushing it"
