# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

include:
  - local: debian/neon-core-models.yml
  - local: debian/neon-core-image-dangerous-iso.yml
  #- local: debian/neon-core-image-signed-iso.yml
