# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/snap-image-dangerous.yml
#      - /gitlab-templates/snap-image-signed.ymlv
default:
  before_script:
    - echo KDECI_GITLAB_TOKEN=$KDECI_GITLAB_TOKEN